spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  albums:
    url: https://jsonplaceholder.typicode.com/albums
  photos:
    url: https://jsonplaceholder.typicode.com/photos